name: aya_isp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  logger: ^2.6.2
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^17.2.3
  firebase_crashlytics: ^5.0.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  network_info_plus: ^4.0.0
  package_info_plus: ^4.0.1
  url_launcher: ^6.1.10
  connectivity_plus: ^6.1.5
  webview_flutter: ^4.0.7
  in_app_update: ^4.2.2
  firebase_performance: ^0.11.1+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo1.png
  min_sdk_android: 21

